services:
    app:
        container_name: mydrive
        image: kylehoell/mydrive:latest
        volumes:
            # Use the following volumes section if you want to use bind mounts:
            # - /path/to/data:/data/
            # - /path/to/temp:/temp/

            # Use the following volumes section if you want to use named volumes:
            - mydrive-data:/data/
            - mydrive-temp:/temp/
        ports:
            - "${HTTP_PORT:-3000}:3000"
            # Optional: Uncomment the following line if you want to use HTTPS
            #- "${HTTPS_PORT:-8080}:8080"

        # Use expose: if using a reverse proxy
        # expose:
        #     - 3000
        #     - 8080
        env_file:
            - .env # Copy .env.example to .env and fill in the values

    mongo:
        image: mongo:8
        container_name: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: username
            MONGO_INITDB_ROOT_PASSWORD: password
        expose:
            - 27017
        volumes:
            - db-data:/data/db
        healthcheck:
            test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
            timeout: 10s
            interval: 10s
            retries: 10
            start_period: 10s

# Use the following volumes section if you want to use named volumes.
volumes:
    mydrive-data:
    mydrive-temp:
    db-data:
